# ================== Server ==================
server.port=9090

# ================== PostgreSQL ==================
spring.datasource.url=jdbc:postgresql://localhost:5656/rentaldb
spring.datasource.username=admin
spring.datasource.password=admin

# Hibernate / JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Connection Pool
spring.datasource.hikari.maximum-pool-size=10

# ================== Keycloak Configuration ==================

# Base Server
keycloak.server-url=http://localhost:8080

# Admin Client (Used for creating users)
keycloak.admin.realm=Rent-wepsite
keycloak.admin.client-id=admin-backend-client
keycloak.admin.username=admin
keycloak.admin.password=12345

# Your Application Realm
keycloak.target.realm=Rent-wepsite

# ================== Spring Security (JWT Validation) ==================
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080/realms/Rent-wepsite
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8080/realms/Rent-wepsite/protocol/openid-connect/certs

# Optional settings
keycloak.use-resource-role-mappings=true
keycloak.bearer-only=true


CLOUDINARY_URL=cloudinary://354294472616711:m7ZgZ3FNXaMfsWHTGMIsdCacmcY@dwji7p5ms