# === PostgreSQL Configuration ===
spring.datasource.url=jdbc:postgresql://localhost:5656/rentaldb
spring.datasource.username=admin
spring.datasource.password=admin

server.port=9090
# Hibernate / JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


# Optional: Connection pool settings
spring.datasource.hikari.maximum-pool-size=10

# ================== Keycloak Configuration ==================

# Admin Client Configuration (for Keycloak Admin API)
# Admin Client Configuration (for Keycloak Admin API)

keycloak.admin.username=admin
keycloak.admin.password=12345
keycloak.admin.client-id=admin-backend-client
keycloak.admin.client-secret=8xniL5HKNZzTnK3nflvj412kmcyJgS6K

# Main Keycloak Settings (for your application)


spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8080/realms/Rent-wepsite/protocol/openid-connect/certs

# Optional but recommended

keycloak.bearer-only=true
keycloak.target.realm=Rent-wepsite
# Increase timeouts for the JWT decoder to prevent Read timed out
spring.security.oauth2.resourceserver.jwt.connect-timeout=5000ms
spring.security.oauth2.resourceserver.jwt.read-timeout=5000ms
keycloak.admin.server-url=http://localhost:8080
# ================== KEYCLOAK / JWT CONFIG ==================


# Optional: Also set issuer for extra validation
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080/realms/Rent-wepsite
cloudinary.cloud_name=dwji7p5ms
cloudinary.api_key=353398222149344
cloudinary.api_secret=YMKEXXtY9sFujFFhE614O2l0yz8

spring.datasource.hikari.max-lifetime=1800000
spring.datasource.hikari.keepalive-time=300000
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

spring.jpa.properties.hibernate.format_sql=true

# Chapa Payment Configuration
chapa.secret-key=CHASECK_TEST-eZFnuLKAHCa0IECVvNBpDbxB7t3ZjNKA
chapa.base-url=https://api.chapa.co/v1
chapa.callback-url=http://localhost:8080/api/payment/callback
chapa.webhook-secret=your-random-secret-hash